# Generated by Django 3.0.7 on 2020-06-17 19:01

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('game', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='game',
            name='other_word',
            field=models.CharField(blank=True, max_length=200, null=True),
        ),
        migrations.AddField(
            model_name='game',
            name='spy',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='game_spy', to='game.GameUser'),
        ),
        migrations.AddField(
            model_name='game',
            name='spy_word',
            field=models.CharField(blank=True, max_length=200, null=True),
        ),
    ]
