# Generated by Django 3.0.7 on 2020-06-18 15:17

import datetime
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('game', '0002_auto_20200617_1901'),
    ]

    operations = [
        migrations.CreateModel(
            name='GameUserWord',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('word', models.CharField(max_length=40)),
                ('posted_at', models.DateTimeField(default=datetime.datetime.now)),
                ('game_user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='game.GameUser')),
            ],
        ),
    ]
