# Generated by Django 3.0.7 on 2020-06-18 16:49

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('game', '0003_gameuserword'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='game',
            name='started',
        ),
        migrations.AddField(
            model_name='game',
            name='status',
            field=models.CharField(choices=[('PENDING', 'Pending'), ('STARTED', 'Started'), ('VOTING', 'Voting')], default='PENDING', max_length=20),
        ),
    ]
