# Generated by Django 3.0.7 on 2020-06-18 19:15

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('game', '0004_auto_20200618_1649'),
    ]

    operations = [
        migrations.AddField(
            model_name='gameuser',
            name='vote',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='game.GameUser'),
        ),
        migrations.AddField(
            model_name='gameuser',
            name='vote_confirmed',
            field=models.BooleanField(default=False),
        ),
    ]
